### PR TITLE
Expand on the data migration instructions

### PR DESCRIPTION
**Pull request by mbaltaks**
I just had to actually go through the process of updating from 9.3 to 9.4 and I took a moment to note the specific steps involved for the few databases I still need. I think this will save some users the time I just spent looking this up again.

### CODE REVIEW

**Comment by jakob** [comment]
Thanks for the pull request, that part of the docs is definitely in need of improvement!

I believe your instructions are missing a step to create databases (otherwise psql -d ... will fail if the database doesn't exist yet), right?

Also, roles and tablespaces are missing (tablespaces probably aren't widely used, but many people add users). We should probably add an optional first step that calls `pg_dumpall --globals-only`.

**Comment by mbaltaks** [comment]
I've not used roles or tablespaces in PostgreSQL, so I've added what I think should work - but I don't know the correct order for restoring - I assume that tablespaces should be restored before databases.

**Comment by jakob** [comment]
Thank you, this looks like it should work! I'll test it as soon as I have some spare time and then merge your pull request if it works correctly.

**Comment by jakob** [comment]
Just tested it, seems to work. Thanks again for submitting this pull request, aologies for taking so long to merge it.

**Pull request merged**
