### PR TITLE
Add a missing PostgreSQL tool for OS X.

### PR DESCRIPTION
**Pull request by lauris**

### CODE REVIEW

**Comment by jakob** [comment]
Thanks for the pull request. I'm not sure it fits in that list, since it looks like this is something you run in a web browser? Do you install it locally? It wasn't clear from the website, and apparently requires an account before I can try it out.

Maybe we could add a section on web based tools? There are others that come to mind, like TeamPostgreSQL, that you could use on a Mac, but aren't really Mac Apps.

**Comment by lauris** [comment]
I think it fits well with other tools because it has the same purpose – to administer and manage a PostgreSQL database. It is also included in [awesome-postgres](https://github.com/dhamaniasad/awesome-postgres#gui) list among other GUI tools.

You run it locally and use via web browser, similar to to a lot of other web-based tools. Datazenit can also be installed on a server and used by multiple users.

**Comment by jakob** [comment]
OK, I'll merge this and add a note that it is web based.

**Comment by lauris** [comment]
Ok, great! Btw the registration will soon not be necessary, you will be able to try out Datazenit without creating an account. 

If you are interested to try it out, I would love to hear your feedback :)

**Pull request merged**
